include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    avoid_function_literals_in_foreach_calls: false
    prefer_constructors_over_static_methods: false
    use_setters_to_change_properties: false
    sort_pub_dependencies: false
    constant_identifier_names: false
    avoid_dynamic_calls: false
